name: Stream


variables:
  - template: configurations\collective.yml

stages:
  - stage: build
    jobs:
      - job:
        pool:
          vmImage: $(vmImage)
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'filePath'
            filePath: $(buildScriptPath)
          displayName: 'Building powered by Powershell'
        - publish: $(artifactToPublishPath)
          artifact: drop

  - stage: deploy_dev
    displayName: Deploy Dev
    dependsOn: build
    condition: succeeded('build')
    variables:
    - template: configuration\dev.yml

    jobs:
    - job:
      pool:
        vmImage: $(vmImage)
      steps:
        - checkout: none

        - download: current
          artifact: drop

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM resource deployment: $(resourceGroup)'
          inputs:
            location: $(location)
            csmFile: $(armPath)
            csmParametersFile: $(armParamsPath)
            overrideParameters: ''
            subscriptionId: $(subscriptionId)
            resourceGroupName: $(resourceGroup)
            ConnectedServiceName: DataBricksWSConnection
            deploymentOutputs: armOutputs
          