name: Stream


variables:
  - template: configurations\collective.yml
  - group: databricks-ws

stages:
  - stage: build
    jobs:
      - job:
        pool:
          vmImage: $(vmImage)
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'filePath'
            filePath: $(buildScriptPath)
          displayName: 'Building powered by Powershell'
        - publish: $(artifactToPublishPath)
          artifact: drop

  - stage: deploy_dev
    displayName: Deploy Dev
    dependsOn: build
    condition: succeeded('build')
    variables:
    - template: configurations\dev.yml

    jobs:
    - job:
      pool:
        vmImage: $(vmImage)
      steps:
        - checkout: none

        - download: current
          artifact: drop

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM resource deployment: $(resourceGroup)'
          inputs:
            location: $(location)
            csmFile: $(armPath)
            csmParametersFile: $(armParamsPath)
            overrideParameters: ''
            subscriptionId: $(subscriptionId)
            resourceGroupName: $(resourceGroup)
            ConnectedServiceName: DataBricksWSConnection
            deploymentOutputs: armOutputs
          
        - task: AzurePowerShell@5
          displayName: Expose arm output variables
          inputs:
            azureSubscription: DataBricksWSConnection
            azurePowerShellVersion: latestVersion
            scriptType: 'InlineScript'
            Inline: |
              $var=ConvertFrom-Json '$(armOutputs)'
              $value=$var.applicationName.value
              Write-Host "##vso[task.setvariable variable=databricksWorkspaceName;]$value"

        - powershell: |
            write-host "applicationName from arm: $(applicationName)"

        - task: AzureFunctionApp@1 # Add this at the end of your file
          inputs:
            azureSubscription: DataBricksWSConnection
            appType: functionAppLinux
            appName: $(applicationName)
            package: $(dropDir)/**/*.zip
